version: '3.1'

services:
  database:
    container_name: store_db
    image: postgres
    environment:
      POSTGRES_USER: store_dev
      POSTGRES_PASSWORD: store_dev
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U store_dev -d store_db"]
      interval: 10s
      retries: 5
      timeout: 6s
    restart: unless-stopped

volumes:
  postgrs: